Ignored mobs (hotfix + color stripping support)
Slimefun-Addon-Community/MobCapturer pull request #28
Opened 2023-01-11 16:32 UTC by mrgeneralq

- Fixed the bug where it would always ignore nameless mobs
- Added color, config.yml no longer requires the color tags in order to detect the mob.

**IMPORTANT**: the ignored-mobs section will override the capture-named-mobs property

2023-01-12 09:36 UTC, ybw0014 requested changes
Also I think we should check `capture-named-mobs` first, if this option is disabled, we don't need to run ignored names check.

2023-01-12 09:36 UTC, ybw0014 commented on src/main/java/io/github/thebusybiscuit/mobcapturer/listeners/PelletListener.java
> +            List<String> strippedMatches = ignoredMobNames.stream()
The list is usually not big, so I don't think we need stream here, a for loop should be enough

2023-01-12 12:13 UTC, mrgeneralq commented on src/main/java/io/github/thebusybiscuit/mobcapturer/listeners/PelletListener.java
> +            List<String> strippedMatches = ignoredMobNames.stream()
- Replaced stream with for loop
- Moved ignored-mobs functionality below the capture-named-mobs

2023-01-12 12:26 UTC, J3fftw1 requested changes

2023-01-12 12:26 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/mobcapturer/listeners/PelletListener.java
> +                if(ignoredMobName.equalsIgnoreCase(strippedEntityName)){
```suggestion
                if (ignoredMobName.equalsIgnoreCase(strippedEntityName)) {
```

2023-01-12 12:26 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/mobcapturer/listeners/PelletListener.java
> +            for(String ignoredMobName: ignoredMobNames){
```suggestion
            for (String ignoredMobName : ignoredMobNames) {
```

2023-01-12 12:58 UTC, J3fftw1 commented on src/main/java/io/github/thebusybiscuit/mobcapturer/listeners/PelletListener.java
>          }
```suggestion
        if (!MobCapturer.getRegistry().getConfig().getBoolean("options.capture-named-mobs") 
        && entity.getCustomName() != null) { 
        	return false;
        }
```

2023-01-12 22:34 UTC, ybw0014 requested changes

2023-01-12 22:34 UTC, ybw0014 commented on src/main/java/io/github/thebusybiscuit/mobcapturer/listeners/PelletListener.java
> +import java.util.stream.Collectors;
is this used anywhere?
```suggestion
```

2023-01-12 22:34 UTC, ybw0014 commented on src/main/java/io/github/thebusybiscuit/mobcapturer/listeners/PelletListener.java
> +        && entity.getCustomName() != null) {
```suggestion
            && entity.getCustomName() != null) { 
```

2023-01-13 00:02 UTC, ybw0014 approved these changes

2023-01-13 00:06 UTC, merged